### ISSUE TITLE
Create AT 11.0 config set

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#10]
Create the config set 11.0 based on next.
Be careful with the contents of base.mk on both config sets.

**Comment by tuliom** [comment]
I suggest to do that after the Binutils 2.28 that is expected to be released soon.

**Comment by rzinsly** [comment]
Binuyils 2.28 was released and integrated on AT next.

**Comment by denilsonm** [comment]
For the sake of organization: a pull request has been opened for this https://github.com/advancetoolchain/advance-toolchain/pull/20
