### ISSUE TITLE
AT 12.0 does not support memfd_create on RHEL 7.6 with kernel-alt 

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1036]
RHEL 7.6 provides a package called kernel-alt based on Linux 4.14 that supports `memfd_create`.
However, as AT 12.0 on RHEL 7 builds with Linux headers 3.10, glibc is not able to provide this syscall wrapper.

**Comment by er-1** [comment]
We haven't planned another release after AT 12.0-5.
Closing.
