### ISSUE TITLE
Drop support for ppc64 BE on AT >= 13.0?

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1093]
AT 13.0 will support the following distributions:

- Debian 10 ppc64le and x86_64
- RHEL 8 ppc64le and x86_64
- SLES 15 ppc64le and x86_64
- Ubuntu 18.04 ppc64le and x86_64

However, it will not provide a big endian runtime environment.
In that case, should AT 13.0 drop support for powerpc64 (BE) from the cross compiler?

**Comment by er-1** [comment]
No objection.

**Comment by rzinsly** [comment]
I Agree.

**Comment by ThinkOpenly** [comment]
I agree as well. Better use of limited resources, and the beauty of open source is that if somebody wishes to produce an AT for BE, they can!

**Comment by tuliom** [comment]
> I agree as well. Better use of limited resources, and the beauty of open source is that if somebody wishes to produce an AT for BE, they can!

Very good point, @ThinkOpenly !  I'm not proposing to remove the arch files.
I'm just suggesting to stop building and distributing the cross compilers for big endian.

**Comment by tuliom** [comment]
This proposal has been implemented in AT 13.0-0.
