### ISSUE TITLE
Re-enable libsanitizer on AT >= 11.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#114]
libsanitizer had to be disabled on GCC stage 4 due to [GCC bug #81066](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81066).

The fix has been backported to FSF's GCC 7 and libsanitizer should be enabled again on AT >= 11.0.

**Comment by rpsene** [comment]
Fixed by PR #117

**Comment by tuliom** [comment]
This patch broke gcc_1 on AT next.

**Comment by tuliom** [comment]
The build failure on gcc_1 was not caused by this patch.  I'm closing this again.
