### ISSUE TITLE
AT12 undefined symbol in libpthread.so.0

### ISSUE THREAD

**Issue by sfantao** [advancetoolchain/advance-toolchain#1191]
I am getting the error:
```
symbol lookup error: /opt/at12.0/lib64/power9/libpthread.so.0: undefined symbol: pthread_mutex_lock
```
when using AT12.0 to compile an application.

If I run readelf on `/opt/at12.0/lib64/power9/libpthread.so.0` I see:
```
214: 000000000000c040  1076 FUNC    WEAK   DEFAULT [<localentry>: 8]    12 pthread_mutex_lock@@GLIBC_2.17
```
but the GLIBC version does not match:
```
$ /opt/at12.0/lib64/libc.so.6 
GNU C Library (GNU libc) stable release version 2.28.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 8.3.1 20190304 (Advance-Toolchain-at12.0) [revision 269374].
libc ABIs: UNIQUE IFUNC ABSOLUTE
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```

Is it possible that AT is trying to get a symbol from the system `libc`? Any workaround that would fix this?

**Comment by tuliom** [comment]
@sfantao, how are you calling the compiler at link stage?
Are you passing -pthread?

**Comment by sfantao** [comment]
> @sfantao, how are you calling the compiler at link stage?
> Are you passing -pthread?

I was not. That seems to have fixed it. I didn't have to do that to use the system GCC though. I'll close this, let me know if this is worth looking deeper.
