### ISSUE TITLE
Support Ubuntu 20.04 on AT > 13.0

### ISSUE THREAD

**Issue by er-1** [advancetoolchain/advance-toolchain#1239]

**Comment by er-1** [comment]
I was able to build AT next for Ubuntu 20.04 on ppc64le.
I'll send a patch once buildbot can handle Ubuntu 20.04 builds.

**Comment by er-1** [comment]
@tuliom do you think AT next will support both Ubuntu 18.04 and Ubuntu 20.04 or only Ubuntu 20.04?

**Comment by er-1** [comment]
#1342 fixed this. Closing.

**Comment by tuliom** [comment]
> @tuliom do you think AT next will support both Ubuntu 18.04 and Ubuntu 20.04 or only Ubuntu 20.04?

Usually we support only the latest distro version.
