### ISSUE TITLE
Remove GCC minmax changes from AT 11.0 during the beta phase

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#128]
There is a TODO in configs/11.0/packages/gcc/sources to remove part of the code there.

This is just a reminder.

**Comment by rpsene** [comment]
remove it all:

atsrc_apply_patches ()
{
	# TODO: remove this on Beta phase.
	set -x
	mv gcc/config/rs6000/rs6000-cpus.def \
	   gcc/config/rs6000/rs6000-cpus.def.back
	sed "s:| OPTION_MASK_P9_MINMAX:/* | OPTION_MASK_P9_MINMAX */:" \
	   gcc/config/rs6000/rs6000-cpus.def.back > \
	   gcc/config/rs6000/rs6000-cpus.def || return ${?}

	patch -p1 < 9d7afb216062.patch || return ${?}

	return 0
}

**Comment by rzinsly** [comment]
The fix for that is being reviewed by https://github.com/advancetoolchain/advance-toolchain/pull/144.
