### ISSUE TITLE
build python with --enable-optimizations and --with-lto

### ISSUE THREAD

**Issue by brihh** [advancetoolchain/advance-toolchain#1321]
we've seen some good performance improvements with local python builds done with the --enable-optimzations (enables profile driven optimizations) and --with-lto. those options do increase the build time, but that won't affect customers. In looking around, it appears that Ubuntu on both power and x86 does --enable-optimizations. RHEL does that on x86 but not power, but we have an issue open with them to enable it for power (issue with them was build time, but power build time isn't that bad.)

this will probably be fixed in a near-future RHEL8.# release, but that won't help current customers on RHEL7.#.

can the python included with AT12 and AT13 be built with those 2 options for improved performance?

thx.bri.

**Comment by tuliom** [comment]
This has been implemented for AT 14.0-0 in PR #1331.
We're now testing and reviewing if this can be backported to older AT versions.

**Comment by ThinkOpenly** [comment]
There is now an open pull request addressing this issue (pull #1404)

**Comment by er-1** [comment]
PR #1404 has been merged.
Next releases including the fix : AT 12.0-3 (May 2020), AT 13.0-2 (June 2020), AT 14.0-0 (August 2020).
