### ISSUE TITLE
Re-add libqt4-dev dependency for Ubuntu 20.04 on AT next

### ISSUE THREAD

**Issue by er-1** [advancetoolchain/advance-toolchain#1354]
The dependency for the `libqt4-dev` package had to be removed from `configs/next/distros/ubuntu20.mk` since it is temporarily unavailable on the repos configured on our build server and builds fail during dependency check, even though all qt4 packages we need are installed in the system.

The dependency should be re-added to `AT_NATIVE_PKGS_REQ` on `configs/next/distros/ubuntu20.mk` as soon as this problem is solved.

**Comment by tuliom** [comment]
I think we can close this issue.  Any objections?

**Comment by mscastanho** [comment]
I tried checking one of our Ubuntu 20.04 build systems for Qt packages, but turns out it has none installed:
```
$ apt list --installed | grep qt
$
```
But AT is building fine. Is this expected? Is Qt really still required to build AT?

**Comment by tuliom** [comment]
@mscastanho AFAIR, it used to be required for a valgrind feature.
But I don't see any references to Qt in the configure logs anymore.
