### ISSUE TITLE
Distribute libnxz on AT 14.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1383]
[libnxz](https://github.com/libnxz/power-gzip) is a library that is API and ABI-compatible with zlib and provides access to the NX GZIP processor available on POWER9 processors.
It's dual-licensed Apache 2.0 and GPLv2.

We'd need version >= 0.60.
I suggest to package it on its own RPM/DEB as it may not be used by all users.

**Comment by tuliom** [comment]
Notice this package is not required on AT <= 13.0.

**Comment by tuliom** [comment]
Reminder: new packages are usually followed by a new FVTR testcase  ;-)

**Comment by er-1** [comment]
@lucmaga The issue #1450 is related with this.

**Comment by er-1** [comment]
#1561 fixes this.
