### ISSUE TITLE
glibc build is failing on cross-compiler for AT 11.0

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#141]
When building AT 11.0 for cross-compiler glibc_1 build is failing with the following error:

checking if /home/rzinsly/AT/opt/at11.0-0-test1/bin/powerpc64le-linux-gnu-gcc -m64 supports binary128 floating point type... no
configure: error: ***  binary128 floating point type (GCC >= 6.2) is required on powerpc64le.

The output in configure.log is:
configure:5: checking if /home/rzinsly/AT/opt/at11.0-0-test1/bin/powerpc64le-linux-gnu-gcc -m64 supports binary128 floating point type
configure:31: /home/rzinsly/AT/opt/at11.0-0-test1/bin/powerpc64le-linux-gnu-gcc -m64 -c -g -O2 -Werror -mfloat128  conftest.c >&5
cc1: error: -mfloat128 requires -mfloat128-type
configure:31: $? = 1

**Comment by gftg85** [comment]
This is a duplicate of #138

**Comment by rzinsly** [comment]
Oops, my bad.
