### ISSUE TITLE
[FVTR] python_pty test failing intermittently on AT >= 10.0

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#146]
The python_pty test is failing sometimes in our Python test case with the following error:

0:01:09 [243/392/1] test_pty failed
test test_pty failed -- Traceback (most recent call last):
  File "/home/tcbot/bot-slave/at_opt/at-next-12.0-0-alpha/lib64/python3.6/test/test_pty.py", line 109, in test_basic
    self.assertEqual(b'For my pet fish, Eric.\n', normalize_output(s2))
AssertionError: b'For my pet fish, Eric.\n' != b'For m'

This is happening on AT 10.0, 11.0 and next, I observed this on SLES 12 and Ubuntu 16.04.

**Comment by rzinsly** [comment]
The test_float is failing as well on SLES 12 and Ubuntu 16.04 for AT next, on Ubuntu 14.04 it's passing.

**Comment by gftg85** [comment]
Do you have an error message?

**Comment by rzinsly** [comment]
@gftg85 I forgot, sorry.
I updated the previous comment.

**Comment by rzinsly** [comment]
The test_float started to fail with glibc's commit ID 70a6707fa15e.
