### ISSUE TITLE
Ubuntu 20.04 does not support FTP repositories

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1544]
@munroesj52 found out the following issue:

```
E: The method 'ftp' is unsupported and disabled by default. Consider
switching to http(s). Set Dir::Bin::Methods::ftp to "ftp" to enable it
again.
E: Failed to fetch
ftp://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/ubuntu/dists/bionic/InRelease

E: Some index files failed to download. They have been ignored, or old ones
used instead.
```

The server already supports HTTP and HTTPS, but the documentation needs to be updated.

**Comment by munroesj52** [comment]
So:
are you going to add fossa?
are you to update the release notes for at13 bionic?

Still some problems:
sudo apt-get install advance-toolchain-at13.0-runtime
advance-toolchain-at13.0-devel advance-toolchain-at13.0-perf
advance-toolchain-at13.0-mcore-libs
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 advance-toolchain-at13.0-runtime : Depends: libffi6 (>= 3.0.4) but it is
not installable
E: Unable to correct problems, you have held broken packages.

**Comment by tuliom** [comment]
> are you going to add fossa?

@munroesj52 , yes.  @er-1 has already added support for focal fossa in AT 14.0.
We do have some alphas, but we don't think it's ready yet:
https://github.com/advancetoolchain/advance-toolchain/tags

> The following packages have unmet dependencies:
>  advance-toolchain-at13.0-runtime : Depends: libffi6 (>= 3.0.4) but it is not installable

Ubuntu 20.04 doesn't provide libffi6 anymore, just libffi7.
