### ISSUE TITLE
Missing mandatory fields from deb control files

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#1563]
I noticed the field `Standards-Version` is missing in the first paragraph of the AT 14.0 deb control file:
https://github.com/advancetoolchain/advance-toolchain/blob/7c94f8029a47af021348ed0a977d5e71f5ced3e1/configs/14.0/deb/monolithic/control#L14-L20

But looks like it is mandatory ([link](https://www.debian.org/doc/debian-policy/ch-controlfields.html#source-package-control-files-debian-control)). 

That is true for other files as well.:
```
[advance-toolchain]$ for f in $(find -name 'control'); do grep -vl Standards-Version $f; done 
./configs/10.0/deb/monolithic/control
./configs/8.0/deb/monolithic/control
./configs/8.0/deb/monolithic_cross/control
./configs/13.0/deb/monolithic/control
./configs/13.0/deb/monolithic_cross/control
./configs/12.0/deb/monolithic/control
./configs/12.0/deb/monolithic_cross/control
./configs/7.1/deb/monolithic/control
./configs/7.1/deb/monolithic_cross/control
./configs/14.0/deb/monolithic/control
./configs/14.0/deb/monolithic_cross/control
./configs/9.0/deb/monolithic/control
./configs/9.0/deb/monolithic_cross/control
./configs/next/deb/monolithic/control
./configs/next/deb/monolithic_cross/control
./configs/11.0/deb/monolithic/control
./configs/11.0/deb/monolithic_cross/control
```

On these same files, the fields `Version` and `Maintainer` for each binary package are also missing, and are also mandatory as per the document linked above.

**Comment by er-1** [comment]
`Standards-Version` makes sense for the packages built and provided by Debian/Ubuntu, which isn't our case.
`Version` and `Maintainer` are mandatory in `DEBIAN/control`, which is a generated file based on the files in the `debian` directory. `Version` is taken from `debian/changelog`. `Maintainer` is taken from the `Maintainer` field in the `Source` section in `debian/control`.
That said, we could update the `compat` level, from 9 to 12 and take advantage of the new features of `debhelper`.

**Comment by tuliom** [comment]
AFAICS, we can close this.  Any objections?
