### ISSUE TITLE
Update GCC on AT 9.0

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#176]
Update GCC to revision 248298 on AT 9.0.

**Comment by rzinsly** [comment]
GCC 5.5 is about to be release: https://gcc.gnu.org/ml/gcc/2017-10/msg00018.html
We should wait for it and get the newest changes.

**Comment by tuliom** [comment]
The latest revision is 253687.  The FSF GCC 5 branch is now closed.

**Comment by racardoso** [comment]
Check PR #212

**Comment by racardoso** [comment]
Closed via c47770e
