### ISSUE TITLE
update_revision.sh wrongly chooses the branch to get updates from

### ISSUE THREAD

**Issue by er-1** [advancetoolchain/advance-toolchain#1779]
Depending on the packages to check, scripts/utilities/update_revision.sh wrongly chooses the branch to get updates from.

For example, AT 13.0 tracks the `tbb_2019` branch of TBB, but the revision value matches more than one branch:
```
$ git branch -r --contains 4bdba61bafc6
  origin/HEAD -> origin/tbb_2020
  origin/tbb_2019
  origin/tbb_2020
```
In this case, the script chooses `HEAD` whereas `tbb_2019` is expected.

**Comment by mscastanho** [comment]
This has been fixed by @er-1 in #1777

**Comment by mscastanho** [comment]
My mistake. That was actually another issue in the same script.

**Comment by mscastanho** [comment]
What if we had a `ATSRC_PACKAGE_BRANCH` var in the sources file to say which branch we are following? That value should not change frequently, as we usually follow master on AT next and a release branch on released AT versions. Then we could stop relying on `git branch -r --contains`.
