### ISSUE TITLE
Cache manager service isn't properly removed

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#179]
I've noticed that AT 11 is leaving some cache manager files on Ubuntu 16.04 after being uninstalled, e.g.:

/etc/systemd/system/multi-user.target.wants/at11.0-0-beta1-cachemanager.service -> /lib/systemd/system/at11.0-0-beta1-cachemanager.service

**Comment by rzinsly** [comment]
Fixed by #345.
