### ISSUE TITLE
Cherbot stopped updating some packages from AT next

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1897]
The last update is from Dec. 5th : #1852 .
This is affecting all AT releases.

**Comment by mscastanho** [comment]
Checking the logs from our `update_rev` cron job, I see many messages like `Unable to connect to git://gcc.gnu.org/git/gcc.git or wrong branch name`, not only for gcc, but for other packages as well.

```
Unable to connect to git://sourceware.org/git/binutils-gdb.git or wrong branch name
Unable to connect to git://sourceware.org/git/glibc.git or wrong branch name
Unable to connect to https://github.com/libdfp/libdfp/archive/1031321fa9d2.tar.gz or wrong branch name
```

I wonder if that has something to do with 8607a59b5a67d6, which was merged on Dec 10th. Still investigating.

**Comment by mscastanho** [comment]
Some `sources` files have missing `ATSRC_PACKAGE_BRANCH` values, which is required since 8607a59, that's likely what is causing the issue. That commit added this var for some, but not all necessary files. That's why some packages are still being updated correctly (like Python on AT next), and others are not.

This is a list of `sources` files for AT 12, 13, 14 and next that do not have that var. Some are symlinks, so I used `realpath` to get the path to the actual file.
```
[configs]$ for f in $(find -name sources -exec grep -L ATSRC_PACKAGE_BRANCH {} \; | grep -e '\(12\|13\|14\|next\)'); do echo $(realpath $f); done | sort | uniq
/home/mscastanho/dev/advance-toolchain/configs/10.0/packages/gmp/sources
/home/mscastanho/dev/advance-toolchain/configs/10.0/packages/libsphde/sources
/home/mscastanho/dev/advance-toolchain/configs/10.0/packages/paflib/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/boost/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/expat/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/libdfp/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/libhugetlbfs/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/libpfm/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/mpc/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/mpfr/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/oprofile/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/tbb/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/tcmalloc/sources
/home/mscastanho/dev/advance-toolchain/configs/12.0/packages/zlib/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/boost/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/expat/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/libhugetlbfs/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/openssl/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/pveclib/sources
/home/mscastanho/dev/advance-toolchain/configs/13.0/packages/tcmalloc/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/boost/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/expat/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/libdfp/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/libhugetlbfs/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/libnxz/sources
/home/mscastanho/dev/advance-toolchain/configs/14.0/packages/pveclib/sources
/home/mscastanho/dev/advance-toolchain/configs/9.0/packages/kernel/sources
/home/mscastanho/dev/advance-toolchain/configs/9.0/packages/libvecpf/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/binutils/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/expat/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/gcc/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/gdb/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/glibc/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/libhugetlbfs/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/libsphde/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/liburcu/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/tcmalloc/sources
/home/mscastanho/dev/advance-toolchain/configs/next/packages/valgrind/sources
```

**Comment by er-1** [comment]
@mscastanho `ATSRC_PACKAGE_BRANCH` isn't required. If it's missing, it assumes `HEAD` branch is tracked.
That said, the issue comes with 8607a59, especialy when tracking the `HEAD` branch. It tries to get `refs/heads/HEAD` instead of `HEAD`.

**Comment by mscastanho** [comment]
> @mscastanho ATSRC_PACKAGE_BRANCH isn't required. If it's missing, it assumes HEAD branch is tracked.

Oh, that's true. You're right.

@er-1 But I don't see how a missing `ATSRC_PACKAGE_BRANCH` would cause `refs/heads/HEAD` to be used, since `HEAD` is explicitly set in that case:
https://github.com/advancetoolchain/advance-toolchain/blob/ac4998a7df1956268a3a40fa1ba3ed9f8656444d/scripts/utilities/update_revision.sh#L154-L164

**Comment by er-1** [comment]
> @er-1 But I don't see how a missing `ATSRC_PACKAGE_BRANCH` would cause `refs/heads/HEAD` to be used, since `HEAD` is explicitly set in that case:
> 
> https://github.com/advancetoolchain/advance-toolchain/blob/ac4998a7df1956268a3a40fa1ba3ed9f8656444d/scripts/utilities/update_revision.sh#L154-L164

Right, but then it's set again there: 
https://github.com/advancetoolchain/advance-toolchain/blob/ac4998a7df1956268a3a40fa1ba3ed9f8656444d/scripts/utilities/update_revision.sh#L162

**Comment by mscastanho** [comment]
@er-1 Oooh, I missed that `else`. Should we get rid of that `else` then and just let the branch be `HEAD` in case ATSRC_PACKAGE_BRANCH is missing?

**Comment by er-1** [comment]
@mscastanho yes. It should also work when a branch is set (so not HEAD).

**Comment by mscastanho** [comment]
@er-1 Nice! Would you do the honors?

**Comment by er-1** [comment]
> @er-1 Nice! Would you do the honors?

Yes. Fixing my own mistake :)
