### ISSUE TITLE
binutils 2.28: internal error, aborting at ../../bfd/elf64-ppc.c:14952 in ppc64_elf_relocate_section

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#19]
Fixed upstream on master with commit ID b1b07054c08eea65ba8d1a9f771796d686f337e5.
And on binutils-2_28-branch with commit ID 0d69827324f704b75ac7e5c2b39219cdd15e790b.

References:
- [Bug report](https://sourceware.org/bugzilla/show_bug.cgi?id=21224)

**Comment by racardoso** [comment]
Closed via  dcea028
