### ISSUE TITLE
Re-enable boost on AT next

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#1925]
Boost library was temporarily disabled on AT next (#1924) while we come up with a fix for a build failure introduced by latest GCC changes. (See #1908 for more details).

Re-enabling it should be as simple as reverting https://github.com/advancetoolchain/advance-toolchain/pull/1924/commits/8a6d11cdbf6c7f53e7d365a7c250df9f6cafdd36

**Comment by tuliom** [comment]
@mscastanho I think you had run a couple of tests with Boost recently. Do you think we can re-enable it now?

**Comment by mscastanho** [comment]
@tuliom Yes, I tried building it no AT recently and saw no errors. I created #2063 for that.
