### ISSUE TITLE
Missing required packages

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#194]
The installation process run some programs which aren't listed as requirements.
They're usually installed in most of the minimum distro installs, but they aren't available in contained environments, e.g. mock.

It's necessary to list at least gawk, grep, sed and systemd.

**Comment by kanarip** [comment]
Please ensure ordering is going to be taken in to account by using (for advance-toolchain-runtime):

```
Requires(pre):      coreutils
Requires(post):     gawk
Requires(pre):      grep
Requires(pre):      rpm
Requires(pre):      sed
Requires(post):     systemd
```

**Comment by kanarip** [comment]
As for `%post`, some segments could better be moved to `%posttrans`:

```
if [[ -f /opt/at11.0/sbin/ldconfig ]]; then
    /opt/at11.0/sbin/ldconfig
fi
```

This ensures that ATs ldconfig picks up on all system libraries that have been installed in the same 'yum install' transaction. This doesn't obsolete the inotify on `/etc/ld.so.cache` for regular run-time situations, but helps the two-shot initialization of build roots in which the systemd service can not run (koji/mock build roots, Docker containers come to mind).
