### ISSUE TITLE
openssl: Missing EVP_KDF symbols on AT 14.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#1969]
An user reported the following missing symbols from libcrypto on AT 14.0:

```
/opt/at14.0/lib/gcc/powerpc64le-linux-gnu/10.2.1/../../../../powerpc64le-linux-gnu/bin/ld: /lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_derive@OPENSSL_1_1_1b'
/opt/at14.0/lib/gcc/powerpc64le-linux-gnu/10.2.1/../../../../powerpc64le-linux-gnu/bin/ld: /lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_ctrl@OPENSSL_1_1_1b'
/opt/at14.0/lib/gcc/powerpc64le-linux-gnu/10.2.1/../../../../powerpc64le-linux-gnu/bin/ld: /lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_CTX_new_id@OPENSSL_1_1_1b'
/opt/at14.0/lib/gcc/powerpc64le-linux-gnu/10.2.1/../../../../powerpc64le-linux-gnu/bin/ld: /lib64/libk5crypto.so.3: undefined reference to `EVP_KDF_CTX_free@OPENSSL_1_1_1b'
```

**Comment by tuliom** [comment]
These functions are available on OpenSSL master branch [for version 3.0](https://github.com/openssl/openssl/blob/master/NEWS.md#major-changes-between-openssl-111-and-openssl-30-under-development).

But Fedora decided to [backport them to OpenSSL 1.1.1](https://src.fedoraproject.org/rpms/openssl/c/5cda1ca091fe7a96730a929b2a0333aabb6b3966) breaking the ABI with upstream builds because they're providing symbols that are not available upstream.

Looking at `abidiff` I noticed the following `EVP_KDF` symbols added to RHEL 8:
```
  EVP_KDF_CTX_free@@OPENSSL_1_1_1b
  EVP_KDF_CTX_new_id@@OPENSSL_1_1_1b
  EVP_KDF_ctrl@@OPENSSL_1_1_1b
  EVP_KDF_ctrl_str@@OPENSSL_1_1_1b
  EVP_KDF_derive@@OPENSSL_1_1_1b
  EVP_KDF_reset@@OPENSSL_1_1_1b
  EVP_KDF_size@@OPENSSL_1_1_1b
  EVP_KDF_vctrl@@OPENSSL_1_1_1b
  ```

**Comment by tuliom** [comment]
The only solution for this is clear: backport `EVP_KDF` to OpenSSL 1.1.1 too.
This brings the cost of maintaining the backport for the life of that AT version.

That brings another issue: will these symbols have to be supported on OpenSSL 3.0?
It's unclear to me if OpenSSL will keep the ABI compatibility with 1.* in the 3.* libraries.
Which means that, if Fedora/RHEL decide to keep supporting 1.1.1 symbols after OpenSSL 3.0 is released, we would also have to keep supporting them.

**Comment by mscastanho** [comment]
Would we have to backport those symbols only for RHEL builds (since the distro package expects those symbols only on RHEL)?

**Comment by tuliom** [comment]
> Would we have to backport those symbols only for RHEL builds (since the distro package expects those symbols only on RHEL)?

@mscastanho I don't think there is a simple yes/no answer to this question.
Are there other distros doing the same thing?
Does AT provides API or ABI compatibility between the supported distros?

For the record: the user that had this issue was able to work around it by recompiling the library using AT.

With that said, I don't think there is much we can do here.  The cost of maintaining out-of-tree functions for 3 years, from an unstable API that is sensitive to security, is just too much for AT IMHO.

I vote to close this issue.  We can reopen or re-evaluate if an user reports it again.

**Comment by ThinkOpenly** [comment]
I think we need to fix this, but I'm not sure how to do so.

Building AT next today on RHEL8 actually completes the build fine, but there are failures in FVTR, including `ck_binaries`. `ck_binaries.exp` calls `built_for_le` from `shared.exp`. `built_for_le` calls the just-built AT version of `readelf`.  This `readelf` is not runnable:
```
$ $AT_DEST/bin/readelf
[AT_DEST]/bin/readelf: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```
The dependency chain is:
```
$ readelf --all $AT_DEST/bin/readelf | grep NEEDED
 0x0000000000000001 (NEEDED)             Shared library: [libctf-nobfd.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libdebuginfod.so.1]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
$ LD_DEBUG=all $AT_DEST/bin/readelf
[edited for brevity]
     file=libctf-nobfd.so.0 [0];  needed by [AT_DEST]/bin/readelf [0]
          (not relevant, ignoring)
     file=libdebuginfod.so.1 [0];  needed by [AT_DEST]/bin/readelf [0]
       trying file=/lib64/libdebuginfod.so.1^M
     file=libc.so.6 [0];  needed by [AT_DEST]/bin/readelf [0]
       trying file=[AT_DEST]/lib64/power9/libc.so.6^M
     file=libcurl.so.4 [0];  needed by /lib64/libdebuginfod.so.1 [0]
       trying file=/lib64/libcurl.so.4^M
     file=libcrypto.so.1.1 [0];  needed by /lib64/libcurl.so.4 [0]
       trying file=[AT_DEST]/lib64/power9/libcrypto.so.1.1^M
     file=libk5crypto.so.3 [0];  needed by /lib64/libcurl.so.4 [0]^M
       trying file=/lib64/libk5crypto.so.3^M
```

In summary,
- AT `readelf` depends on `libdebuginfod`
- System `libdebuginfod` depends on `libcurl` (??)
- System `libcurl` depends on `libcrypto` and `libk5crypto`
- System `libk5crypto` depends on `libcrypto`
- AT provides `libcrypto` without the `EVP_KDF_ctrl` symbol. (The system libcrypto provides that symbol.)

Some possible approaches:
- Remove `readelf` dependency on `libdebuginfod`. I'm guessing this removes functionality that may be expected in a `readelf` command, although the system `readelf` command has a shockingly low number of dependencies (really only `libdl`) compared to the AT `readelf` (29!). This may be a good thing to investigate.
- Add `libdebuginfod` to AT and remove the dependence on `libcurl`. `libdebuginfod` is in the `elfutils-debuginfod-client` package. This package only contains the `debuginfod-find` command and the library, so this is at least well-contained. There would likely be a loss of expected functionality, unless we can make things dynamically loadable, which would take effort.
- Add `libk5crypto` to AT and remove `EVP_KDF_ctrl` symbol dependence. `libk5crypto` is part of `krb5-libs` package, which is security-sensitive (additional work and risk), has 8(!) other shared objects, and may lose important functionality without the `EVP_KDF_ctrl` symbol.
- Stop providing `libcrypto` in AT. I'm not sure what the implications are here. `libcrypto` is in the same package as `libssl`. Is there a significant performance advantage with the AT versions of these libraries?

The AT `objdump` command has this same issue.

**Comment by tuliom** [comment]
> I think we need to fix this, but I'm not sure how to do so.
> 
> Building AT next today on RHEL8 actually completes the build fine, but there are failures in FVTR, including `ck_binaries`. `ck_binaries.exp` calls `built_for_le` from `shared.exp`. `built_for_le` calls the just-built AT version of `readelf`. This `readelf` is not runnable:

This is only true if the server has `elfutils-debuginfod-client-devel` installed.

>  Remove `readelf` dependency on `libdebuginfod`.

Binutils supports `--with-debuginfod=no`.
We could disable this support only for RHEL 8.

> I'm guessing this removes functionality that may be expected in a `readelf` command, although the system `readelf` command has a shockingly low number of dependencies (really only `libdl`) compared to the AT `readelf` (29!). This may be a good thing to investigate.

I don't see that difference.

Another option is to backport the patches to AT when building on RHEL 8.
But before we decide taking this path, I think we have to answer the questions raised in [this comment](https://github.com/advancetoolchain/advance-toolchain/issues/1969#issuecomment-780576153).

**Comment by ThinkOpenly** [comment]
> > I think we need to fix this, but I'm not sure how to do so.
> > Building AT next today on RHEL8 actually completes the build fine, but there are failures in FVTR, including `ck_binaries`. `ck_binaries.exp` calls `built_for_le` from `shared.exp`. `built_for_le` calls the just-built AT version of `readelf`. This `readelf` is not runnable:
> 
> This is only true if the server has `elfutils-debuginfod-client-devel` installed.
> 
> > Remove `readelf` dependency on `libdebuginfod`.
> 
> Binutils supports `--with-debuginfod=no`.
> We could disable this support only for RHEL 8.

only for RHEL8? Why not generally?

> > I'm guessing this removes functionality that may be expected in a `readelf` command, although the system `readelf` command has a shockingly low number of dependencies (really only `libdl`) compared to the AT `readelf` (29!). This may be a good thing to investigate.
> 
> I don't see that difference.

I don't see it now, either. I can't explain, and will try again to reproduce.

> Another option is to backport the patches to AT when building on RHEL 8.
> But before we decide taking this path, I think we have to answer the questions raised in [this comment](https://github.com/advancetoolchain/advance-toolchain/issues/1969#issuecomment-780576153).

I'm not in favor of carrying these out-of-tree patches indefinitely unless we have no better choice.

**Comment by ThinkOpenly** [comment]
I built twice, once with `--with-debuginfod=no` and once without. Perhaps confusingly, the trees were under `with` (debuginfod, in other words, without the option to disable it; this is the default case) and `without` (which specifies the option to disable debuginfod).

`ldd` shows the huge difference in dependencies between these two builds:
```
$ ldd /home/pc/optwithout/at-next-16.0-0-pc/bin/readelf
        linux-vdso64.so.1 (0x00007fffb8fd0000)
        libctf-nobfd.so.0 => /home/pc/optwithout/at-next-16.0-0-pc/lib64/libctf-nobfd.so.0 (0x00007fffb8f60000)
        libc.so.6 => /home/pc/optwithout/at-next-16.0-0-pc/lib64/power9/libc.so.6 (0x00007fffb8cf0000)
        /home/pc/optwithout/at-next-16.0-0-pc/lib64/ld64.so.2 => /lib64/ld64.so.2 (0x00007fffb8ff0000)
$ ldd /home/pc/optwith/at-next-16.0-0-pc/bin/readelf
        linux-vdso64.so.1 (0x00007fff8d8e0000)
        libctf-nobfd.so.0 => /home/pc/optwith/at-next-16.0-0-pc/lib64/libctf-nobfd.so.0 (0x00007fff8d870000)
        libdebuginfod.so.1 => /lib64/libdebuginfod.so.1 (0x00007fff8d820000)
        libc.so.6 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libc.so.6 (0x00007fff8d5b0000)
        libcurl.so.4 => /lib64/libcurl.so.4 (0x00007fff8d4e0000)
        /home/pc/optwith/at-next-16.0-0-pc/lib64/ld64.so.2 => /lib64/ld64.so.2 (0x00007fff8d900000)
        libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007fff8d490000)
        libidn2.so.0 => /lib64/libidn2.so.0 (0x00007fff8d450000)
        libssh.so.4 => /lib64/libssh.so.4 (0x00007fff8d390000)
        libpsl.so.5 => /lib64/libpsl.so.5 (0x00007fff8d350000)
        libssl.so.1.1 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libssl.so.1.1 (0x00007fff8d270000)
        libcrypto.so.1.1 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libcrypto.so.1.1 (0x00007fff8ced0000)
        libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007fff8ce40000)
        libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007fff8cd00000)
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007fff8ccc0000)
        libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007fff8cc90000)
        libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007fff8cc00000)
        liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007fff8cbc0000)
        libbrotlidec.so.1 => /lib64/libbrotlidec.so.1 (0x00007fff8cb90000)
        libz.so.1 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libz.so.1 (0x00007fff8cb40000)
        libpthread.so.0 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libpthread.so.0 (0x00007fff8cb10000)
        libunistring.so.2 => /lib64/libunistring.so.2 (0x00007fff8c960000)
        librt.so.1 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/librt.so.1 (0x00007fff8c930000)
        libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007fff8c8f0000)
        libdl.so.2 => /home/pc/optwith/at-next-16.0-0-pc/lib64/libdl.so.2 (0x00007fff8c8c0000)
        libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007fff8c890000)
        libresolv.so.2 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libresolv.so.2 (0x00007fff8c850000)
        libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007fff8c800000)
        libm.so.6 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libm.so.6 (0x00007fff8c6f0000)
        libbrotlicommon.so.1 => /lib64/libbrotlicommon.so.1 (0x00007fff8c6b0000)
        libselinux.so.1 => /lib64/libselinux.so.1 (0x00007fff8c650000)
        libcrypt.so.1 => /home/pc/optwith/at-next-16.0-0-pc/lib64/power9/libcrypt.so.1 (0x00007fff8c600000)
        libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fff8c550000)
```

The `with` build still fails as before, not surprisingly:
```
$ tail ~/tmpwith/screenlog.0 
**************** TEST SUMMARY *****************
Passed tests: 31
Skipped tests: 13
Failed tests: 5
***********************************************
make: *** [Makefile:851: /home/pc/tmpwith/at16.0-0-pc.redhat-8_ppc64le_ppc64le/receipts/fvtr.rcpt] Error 1
```
Nicely, the `without` build succeeds:
```
$ tail ~/tmpwithout/screenlog.0 

**************** TEST SUMMARY *****************
Passed tests: 36
Skipped tests: 13
Failed tests: 0
***********************************************
```

I propose we add `--with-debuginfod=no` to binutils `stage_2` (and probably `stage_1` as well), generally (not limited to just RHEL8). Objections?

**Comment by tuliom** [comment]
> only for RHEL8? Why not generally?

@ThinkOpenly because RHEL 8 is the only distro causing issues.

> I propose we add --with-debuginfod=no to binutils stage_2 (and probably stage_1 as well), generally (not limited to just RHEL8). Objections?

I do not object, but I don't understand why it's a good idea to forcibly disable it for the other distros.
I wouldn't be surprised if they're disabled automatically due to the lack of `elfutils-debuginfod-client-devel` in the system.

**Comment by ThinkOpenly** [comment]
> > only for RHEL8? Why not generally?
> 
> @ThinkOpenly because RHEL 8 is the only distro causing issues.
> 
> > I propose we add --with-debuginfod=no to binutils stage_2 (and probably stage_1 as well), generally (not limited to just RHEL8). Objections?
> 
> I do not object, but I don't understand why it's a good idea to forcibly disable it for the other distros.

There is value in having a consistent product across distributions, and value in simpler code which avoids special cases.

> I wouldn't be surprised if they're disabled automatically due to the lack of `elfutils-debuginfod-client-devel` in the system.

...Which means 2 things:

1. It won't be noticed that it is disabled, and
2. Leaving it "possibly enabled, depending on whether the package is installed on the build system" opens up the possibility of running into the same errors at some future point in time. This doesn't seem like _the way_ to me. Builds on similar systems should be predictably similar.

All that being said, I don't have an unwaveringly strong opinion. A successful build on RHEL8 is the primary goal.

Note to self: AT13 builds also fail on RHEL8, so whatever fix needs to reach back that far.

**Comment by rzinsly** [comment]
I agree with @ThinkOpenly that this could be removed from all builds.
Besides of having a consistent product, right now is only failing on RHEL8 but it is likely to fail on RHEL9 and other future distros.
IMO in the future it is best to disable on all builds or backport the patches to AT with the downside stated in c4493b3.

**Comment by tuliom** [comment]
May we create an issue/task in order to guarantee we won't forget to remove this after OpenSSL is merged into AT next?

**Comment by ThinkOpenly** [comment]
> May we create an issue/task in order to guarantee we won't forget to remove this after OpenSSL is merged into AT next?

Specifically, OpenSSL **3** ?

**Comment by tuliom** [comment]
Yes
