### ISSUE TITLE
GPG public key is missing from distro diretories

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#2031]
The AT documentation points to a GPG public key in the distro directory, e.g.
https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/redhat/RHEL7/gpg-pubkey-6976a827-5164221b

However, that key is missing from:
https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/redhat/RHEL8/
https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/suse/SLES_15/

**Comment by er-1** [comment]
The GPG public key is now available from those directories:
https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/redhat/RHEL8/
https://public.dhe.ibm.com/software/server/POWER/Linux/toolchain/at/suse/SLES_15/
