### ISSUE TITLE
Installation error due to cachemanager.service not found

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#2107]
I built an AT-next for RHEL 8  using commit ID 9c4897bb and I noticed the following error while installing it:

```
Running transaction
  Preparing        :                                                                                       1/1 
  Running scriptlet: advance-toolchain-at15.0-alpha-runtime-15.0-0.ppc64le                                 1/8 
  Installing       : advance-toolchain-at15.0-alpha-runtime-15.0-0.ppc64le                                 1/8 
  Running scriptlet: advance-toolchain-at15.0-alpha-runtime-15.0-0.ppc64le                                 1/8 
Failed to restart at150-0-alpha-cachemanager.service: Unit at150-0-alpha-cachemanager.service not found.
warning: %post(advance-toolchain-at15.0-alpha-runtime-15.0-0.ppc64le) scriptlet failed, exit status 5

Error in POSTIN scriptlet in rpm package advance-toolchain-at15.0-alpha-runtime
```

The file was indeed available in the package, so there is something else missing.

**Comment by er-1** [comment]
Same issue using commit ID d7a46e1.

The `postinstall` scriptlet ends with:
```
systemctl --no-reload preset at150-0-alpha-cachemanager.service 
systemctl restart at150-0-alpha-cachemanager.service
```

I got rid of the issue either by removing `--no-reload` or by adding the following line before the `restart`:
```
systemctl daemon-reload
```

I wonder why `--no-reload` is causing issue these days, it has been there for so long. Was it silently failing since the beginning?

**Comment by tuliom** [comment]
> Was it silently failing since the beginning?

I expected a reload was required for this task.
I suspect `--no-reload` was not intended to be used with preset because [the documentation](https://www.freedesktop.org/software/systemd/man/systemctl.html#--no-reload) only mentions `enable` and `disable`.
Maybe a recent modification in systemctl is now causing it to work with preset?
