### ISSUE TITLE
`update_revision.sh` treats URL to tar.gz file as SVN URL

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#2226]
On AT 13, we download Python source code as tarball, instead of using the git repo:

https://github.com/advancetoolchain/advance-toolchain/blob/25d72e8236654e4f4c1cb32985f5271ce49b26fd/configs/13.0/packages/python/sources#L32

When `update_revision.sh` parses `ATSRC_PACKAGE_CO`, it detects it as an SVN URL and tries to run `svn` on it:

https://github.com/advancetoolchain/advance-toolchain/blob/25d72e8236654e4f4c1cb32985f5271ce49b26fd/scripts/utilities/update_revision.sh#L205-L208

Which is causing issues when the automated update script is run:
```
Sat Jul  3 01:05:51 EDT 2021 - python 13.0
svn: warning: W170000: URL 'https://github.com/python/cpython/archive/13c94747c744.tar.gz' non-existent in revision 285718

svn: E200009: Could not display info for all targets because some targets don't exist
Unable to connect to https://github.com/python/cpython/archive/13c94747c744.tar.gz or wrong branch name
```

Note this does not happen with later AT versions because their `sources` file set `ATSRC_PACKAGE_CO` to clone the git repo directly.

**Comment by er-1** [comment]
PR #2227 fixes `configs/13.0/packages/python/sources`, among others updates.
That said, `update_revision.sh`needs a changes to handle properly tar.gz files.
