### ISSUE TITLE
Remove libhugetlbfs from AT 15

### ISSUE THREAD

**Issue by mscastanho** [advancetoolchain/advance-toolchain#2272]
`libhugetlbfs` uses malloc hooks from glibc that were marked as deprecated since glibc 2.32, and now on 2.34 they have been completely removed, preventing it to build against latest glibc (#2260).

There have been discussions upstream about this issue libhugetlbfs/libhugetlbfs#52 but a solution has not been provided yet.

We can probably comment parts of the code to allow most of it to build on AT next while we wait for a definitive fix, but we may need a different approach in the short term for AT 15.

So, should we remove libhugetlbfs from the AT 15?

**Comment by tuliom** [comment]
No, not yet.
We have to find a way to disable the build of the morecore feature into libhugetlbfs and continue distributing it because it still helps a few programs.
With that said, I'm closing this proposal.
