### ISSUE TITLE
Add a new requirement for AT next

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#243]
When pull request #199 is merged, MPFR will depend on AX_PTHREADS that is available in the package autoconf-archive.

**Comment by racardoso** [comment]
@tuliom Can you give more info about this issue? PR #199 was already merged, I've compiled AT next and did not notice any errors. It's something related with performance or anything else?

**Comment by tuliom** [comment]
It means `AT_*_PKGS_REQ` have to be updated to include the new build requirement.

**Comment by munroesj52** [comment]
Yet another case where ./remake.sh does not work. Requires a reset to rerun autoconf after installing autoconf-archive.

**Comment by tuliom** [comment]
Done.
