### ISSUE TITLE
Fix gold for bad .got/.toc layout in AT 15.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#2441]
There are at least 3 patches fixing this on master:

https://sourceware.org/git?p=binutils-gdb.git;a=commitdiff;h=a19da04b3c3a01699aaf7a59b03f5f008355b23d
https://sourceware.org/git?p=binutils-gdb.git;a=commitdiff;h=f19c3684a6db145f57048bff5485fec6e3dd0f76
https://sourceware.org/git?p=binutils-gdb.git;a=commitdiff;h=a1251fdcb58f99644c49b65d72507706f2d40200

They're being tested now and are expected to be backported to `binutils-2_37-branch`.

**Comment by er-1** [comment]
The patches were taken in account with commit 110c7b3
