### ISSUE TITLE
Error using libcrypt.so on AT15.0 in Ubuntu-focal

### ISSUE THREAD

**Issue by fabiane-watanabe** [advancetoolchain/advance-toolchain#2827]
In the latest release of Ubuntu e Fedora, libcrypt.so is provided by "libxcrypt" project, instead of Glibc.

How to reproduce:
Ubuntu : 20.04
AT :15.0

**Comment by tuliom** [comment]
More details: distros have been configuring glibc with `--disable-crypt`, e.g. https://launchpadlibrarian.net/596537387/buildlog_ubuntu-focal-ppc64el.glibc_2.31-0ubuntu9.9_BUILDING.txt.gz

I suspect this could cause issues to programs built with AT 15.0.  Need to confirm if libxcrypt is ABI-compatible with glibc 2.34, before changing AT 15.0.

AT next should definitely be modified though.

**Comment by tuliom** [comment]
> I suspect this could cause issues to programs built with AT 15.0. Need to confirm if libxcrypt is ABI-compatible with glibc 2.34, before changing AT 15.0.

According to libxcrypt's documentation:

> On Linux-based systems, by default libxcrypt will be binary backward compatible with the libcrypt.so.1 shipped as part of the GNU C Library. This means that all existing binary executables linked against glibc’s libcrypt should work unmodified with this library’s libcrypt.so.1.

While this does not answer the previous question, it does look promising.
