### ISSUE TITLE
tcmalloc fails to compile ppc (32 bits) on AT 11.0 and next

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#29]
The reported error is:

`In file included from src/stacktrace_impl_setup-inl.h:51:0,
                 from src/stacktrace.cc:129:
src/stacktrace_powerpc-linux-inl.h: In function ‘int GetStackTrace_ppc(void**, int, int)’:
src/stacktrace_powerpc-linux-inl.h:203:11: error: ‘siginfo_t’ does not name a type; did you mean ‘sigset_t’?
           siginfo_t info;
           ^~~~~~~~~
           sigset_t`

Needs to be investigated and fixed.

**Comment by tuliom** [comment]
I updated the title because this is also happening when building ppc32 on a ppc64 system.

**Comment by RajalakshmiS** [comment]
created PR https://github.com/gperftools/gperftools/pull/883

**Comment by RajalakshmiS** [comment]
Merged
