### ISSUE TITLE
ubuntu packaging - moving files between packages needs special management

### ISSUE THREAD

**Issue by grooverdan** [advancetoolchain/advance-toolchain#353]
<pre>
Preparing to unpack .../advance-toolchain-at10.0-cross-ppc64le_10.0-6_amd64.deb ...
Unpacking advance-toolchain-at10.0-cross-ppc64le (10.0-6) over (10.0-5) ...
dpkg: error processing archive /var/cache/apt/archives/advance-toolchain-at10.0-cross-ppc64le_10.0-6_amd64.deb (--unpack):
 trying to overwrite '/opt/at10.0/share/man/man5/powerpc64le-linux-gnu-gdbinit.5', which is also in package advance-toolchain-at10.0-cross-common 10.0-5
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Preparing to unpack .../advance-toolchain-at10.0-cross-ppc64_10.0-6_amd64.deb ...
Unpacking advance-toolchain-at10.0-cross-ppc64 (10.0-6) over (10.0-5) ...
Preparing to unpack .../advance-toolchain-at10.0-cross-common_10.0-6_amd64.deb ...
Unpacking advance-toolchain-at10.0-cross-common (10.0-6) over (10.0-5) ...
</pre>

<pre>
dpkg -l | grep advance-toolchain
iU  advance-toolchain-at10.0-cross-common  10.0-6                                       amd64        Advance Toolchain cross compiler common files
iU  advance-toolchain-at10.0-cross-ppc64   10.0-6                                       amd64        Advance Toolchain cross compiler
ii  advance-toolchain-at10.0-cross-ppc64le 10.0-5                                       amd64        Advance Toolchain cross compiler
# apt upgrade advance-toolchain-at10.0-cross-ppc64le
Reading package lists... Done
Building dependency tree
Reading state information... Done
You might want to run 'apt-get -f install' to correct these.
The following packages have unmet dependencies:
 advance-toolchain-at10.0-cross-ppc64le : Depends: advance-toolchain-at10.0-cross-common (= 10.0-5) but 10.0-6 is installed
E: Unmet dependencies. Try using -f.
<pre>

**Comment by rzinsly** [comment]
Some arch-specifc manpages were mistakenly placed in the cross-common package, this was fixed by #234.
Thanks for catching it. I updated the known issues in our documentation, there's not much more to do.
