### ISSUE TITLE
[fvtr] Oprofile and Python tests leave files behind

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#354]
After running the Oprofile FVTR test the oprofile_data directory and its files is left at fvtr/ directory.
After running the Python tests some tmp files are left in the test directory.

This could affect the next tests as this is not removed even after a cleanall.

**Comment by tuliom** [comment]
> After running the Python tests some tmp files are left in the test directory.

This only happens when the test fails.

**Comment by tuliom** [comment]
Adding more information: make cleanall does try to remove Python files.
But there seems to be a new Python test that creates directories without read and write permission.
That's why cleanall has been failing.
