### ISSUE TITLE
Experence building AT for BE G5/970 Ubuntu 14.04

### ISSUE THREAD

**Issue by munroesj52** [advancetoolchain/advance-toolchain#430]
I have a still working G5 PPC64 quad with 8GB and 1TB drive.
Yes I know it is NOT SUPPORTED. But this is Open source, and I am retired, so ...

There is a working Ubuntu 14.04 Install that supports POWER5 and 970 (Apple G5 and IBM JS20 blades): https://wiki.ubuntu.com/PowerPCDownloads

This installs a PPC64 kernel but the user land is largely 32-bit with some 64-bit libraries for gcc/g++/glibc. The trick is to find the correct package name spelling for apt-get:
sudo apt-get install lib64stdc++6 libc6-dev-ppc64 lib64stdc++6 libstdc++-4.8-dev
lib64gomp1 lib64gcc1 lib64atomic1 lib64asan0 lib64expat1 lib64gcc-4.8-dev 
lib64tinfo5  lib64readline6  lib64ncurses5 lib64ncurses5-dev  lib64bz2-1.0  lib64bz2-dev

There is a gdb64 package but you have to remember to use the gdb64 command to debug any 64-bit programs.

This will allow you to compile and execute C/C++ 64-bit applications if they don't require too many (64-bit) libraries. For most interesting projects you may find key 64-bit libraries or tool are missing and you will have to (try to) build the prerequisites your self.

Now the Advance Toolchain (AT) could help by providing: a complete biarch (32/64-bit) compiler and runtime, additional 64-bit libraries (like boost, OpenSSL, ...) and 64-bit tools (operf, valgrind, libpfm).

But the last version of AT that supported 970 was AT5.0 which does not support Ubuntu (requires at least AT7.1 get a version compatible GLIBC). Technically any AT before AT9.0 is out of support.

But thanks to Tulio and Raphael we have this project to open source the build tools for AT. This should allow the sufficiently motivated person to build a working AT for this environment. 

<end of part 1>

**Comment by munroesj52** [comment]
<begin part 2> 

So we have partial 64-bit environment after installing Ubuntu 14.04 powerpc on a PowerMAC G5 (PPC970). So installing a version of the Advance Toolchain (AT) will improve the situation by providing additional libraries and important tools. But the last AT that supported 970 was AT5.0, which too old (back level GLIBC version). So we will try to built an AT version specifically target at the 970 chip (PowerISA 2.01 with VMX, AKA Altivec).

The first version of AT that supported Ubuntu was AT7.1 and that was Little Endian (LE) only. AT 7.0 was supported on Debian Precise as i386 POWER7/8 cross toolchain. AT7.0 Big Endian (BE) native only supported RHEL and SLES.

So we need to select a AT7.0 or newer build and adapt the build scripts to support Ubuntu Trusty (14.04) Native Big Endian. AT7.0 supports  BE (BUILD_ARCH := ppc64) but only targets power7 and later. Also the AT7.0 Sanity test does not include Ubuntu. So we need to edit build.mk (advance-toolchain/configs/7.0/build.mk) and add a ubuntu-14.mk file (advance-toolchain/configs/7.0/distros/ubuntu-14.mk)

<saved, need more edits>

**Comment by munroesj52** [comment]
Tried to build AT_CONFIGSET=7.1 BUILD_ARCH=ppc64 for BUILD_LOAD_ARCH := 970 and found that hard way that newer GLIBC (at least 2.19 and 2.20) are broken for multilib and 970. I would guess that by the time multilib support was added, 970 (PMAC G5 and IBM JS20) was "out of support".

Net the GLIBC stage-2 fails with duplicate symbols

Putting this aside. I thought a AT8.0 (which supports both BE/LE and Ubuntu) "should work" if I configured for a base power4 -mtune=970 and added power5 power6 as multilibs.

Worked though the previously problems (above) plus found the python build failed because the configure would not find the 64-bit versions of libpanel and libbz2. The followed work around worked:

sudo apt-get install lib64bz2-dev lib64ncurses5-dev

cd /usr/lib/powerpc64-linux-gnu
sudo cp /usr/lib64/libpanel.a /usr/lib64/libpanel.so.5.9 .
ln -s /usr/lib64/libpanel.so.5.9 libpanel.so
ln -s /usr/lib64/libpanel.so.5.9 libpanel.so.5

sudo cp /usr/lib64/libbz2.a /usr/lib64/libbz2.so.1.0.4 .
ln -s /usr/lib64/libbz2.so.1.0.4 libbz2.so
ln -s /usr/lib64/libbz2.so.1.0.4 libbz2.so.1
ln -s /usr/lib64/libbz2.so.1.0.4 libbz2.so.1.0

/opt/at8.0/sbin64/ldconfig

This allowed python and gdb to build. Then valgind failed with the kernel version check (updated configure.ac to include 4.*) and restarted. Then built 64-bit boost without complaint.

At this point I was getting hopeful at build moved to "Begin DEB packaging for 8.0-8..."  the AT scripting claimed success but not deb files could NOT be found. Looking at the build log I see: lots of these errors:

ERROR: ld.so: object 'libfakeroot-sysv.so' from LD_PRELOAD cannot be preloaded: ignored.

Seems the PPC64 Ubuntu builds only includes a 32-bit libfakeroot-sysv.so. Looks liek Stewart is the expert on this and hope he will respond the helpful clues.

**Comment by munroesj52** [comment]
Tried to build my own libfakeroot-sysv.so with total failure. I just don't understand how they want me to build this thing.

types are missing with requires install of libcap-dev. But that install causes the libfakeroot configure to turn on a bunch of xattr crap that blows chunks because parameter types DO NOT MATCH not what is in ./linux/capability.h. 

undef HAVE_SETXATTR  HAVE_FSETXATTR  HAVE_LSETXATTR in config.h and it will compile but make check fails.

Not a happy camper

**Comment by munroesj52** [comment]
the 64-bit fakeroot did not work out. The problem is too many tools (bash, make, etc) are still 32-bit. So which ever you pick (32 or 64) part of the build with be the wrong size for libfakeroot.so.

The net seems to be that fakeroot just does not work for biarch.

Next I tried replacing fakeroot with sudo, Not joy so far :(

**Comment by munroesj52** [comment]
One of the last issues was valgrind.

valgrind configure is unhappy with the ubuntu 14.04 4.4 kernel (LTS-5
remember upgrades the kernel). So simple patch.

diff -paurN valgrind-3.10.0/configure.ac vg-310-itrace/configure.ac
--- valgrind-3.10.0/configure.ac        2014-09-11 04:12:44.000000000
-0500
+++ vg-310-itrace/configure.ac  2014-11-12 10:43:27.598185054
-0600
@@ -303,7 +303,7 
         kernel=`uname -r`
 
         case "${kernel}" in
-             2.6.*|3.*|4.*) 
+             2.6.*|3.*) 
                    AC_MSG_RESULT([2.6.x/3.x family (${kernel})])
                    AC_DEFINE([KERNEL_2_6], 1, [Define to 1 if you're
using Linux 2.6.x or Linux 3.x])
                    ;;

The trick is that by the time you find this the at build are at least three copies of valgrind source. SO if you patch ./sources/valgrind ./remake.sh will just use the patched copy in ./at${AT_VER}.$(AT_DISTRO)/sources/valgrind. 

So you need to remove the receipts before patching ./sources/valgrind-$VERSION-$REVISION/configur.ac. Then you can ,/remake.sh which will propagate the configure.ac patch through the build.

**Comment by tuliom** [comment]
This was very informative.
I'm closing this issue and keep the information archived in case someone tries to do the same.

**Comment by munroesj52** [comment]
Ok, I just wanted to log the details in case someone else tries it.
