### ISSUE TITLE
sqlite3 python issue with AT9 and AT10

### ISSUE THREAD

**Issue by cristianomalossi** [advancetoolchain/advance-toolchain#45]
I am experiencing an issue while loading sqlite3 from AT9 on a Minsky with RHEL7.3
 
```
> python3
Python 3.4.3 (default, Feb  1 2017, 14:32:30)
[GCC 5.3.1 20170120 (Advance-Toolchain-at9.0) [ibm/gcc-5-branch revision 244812 on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> os.path()
KeyboardInterrupt
>>> import sqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'sqlite'
>>> import sqlite3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/at9.0/lib64/python3.4/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/opt/at9.0/lib64/python3.4/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named '_sqlite3'
>>>
```
 
I have installed on RHEL the sqlite package:

> sqlite-devel
 
but I cannot do anything with pip to upgrade the python installation:

>  pysqlite is not supported on Python 3. When using Python 3, use the sqlite3 module from the standard library.

I think there is an issue with AT9 installation - probably that _sqlite3 file is missing.
The same issue appears with AT10.

You can also take a look at this page where they suggest to re-build python to fix it:
[No-module-named-sqlite3](http://stackoverflow.com/questions/1210664/no-module-named-sqlite3)

Can you please check?

Many thanks,

Cristiano MALOSSI

> Research Staff Member
> IBM Research - Zurich
> Foundations of Cognitive Solutions
> Säumerstrasse 4, 8803 Rüschlikon - Switzerland
> tel: +41 44 724 8616
> e-mail: acm@zurich.ibm.com
> www: http://ibm.biz/cristiano_malossi

**Comment by rpsene** [comment]
by default the support is not activated. It is necessary to use --enable-loadable-sqlite-extensions during the configure process and install the libsqlite3-dev.

**Comment by rpsene** [comment]
ubuntu@at-firstbuild:~/python_build/cpython$ ./python 
Python 3.4.6+ (default, May  8 2017, 14:08:33) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
>>>

**Comment by cristianomalossi** [comment]
Can you add --enable-loadable-sqlite-extensions in the AT9/AT10 (and future) python built? Since it comes as RPM, users cannot enable it a posteriori.

**Comment by rpsene** [comment]
This issue was fixed and is available for the versions >= 8 of AT.
