### ISSUE TITLE
Diverge AT 12.0 from next

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#450]
GCC 8.1 RC has just [been announced](https://gcc.gnu.org/ml/gcc/2018-04/msg00157.html).

That means a GCC 8 branch exists and will start to diverge from trunk.
It's time to also diverge the the AT 12.0 config set from AT next.

**Comment by gftg85** [comment]
Apart from switching to the stable branch of GCC, we also have to switch to the stable branch of OpenSSL, once we cut the AT 12.0 branch.

Unless we believe that OpenSSL 1.1.1 will be released before our freeze.

**Comment by tuliom** [comment]
I agree it's the safest decision.  The same thing should apply to all other packages.

**Comment by tuliom** [comment]
The config set has been diverged, but most packages are still waiting for updates.
