### ISSUE TITLE
GCC revision does not match

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#497]
AT 11.0-3 was released with GCC rev. 257474, however, if I run `/opt/at11.0/bin/gcc -v` I get:
`gcc version 7.3.1 20180207 (Advance-Toolchain-at11.0) [ibm/gcc-7-branch revision 257393] (GCC)`

The revision information is stored in file `gcc/REVISION`, which does have a wrong value.

This file is not stored in the repository and is created automatically by `contrib/gcc_update`.

Later, the Advance Toolchain build manipulates this file on GCC stage 1.  The changes from this step are not working anymore.

So, we likely have 2 issues there:
1. `contrib/gcc_update --touch` needs to be executed after the checkout to guarantee we have the correct revision on 'gcc/REVISION'.
2. It's necessary to fix the pre hacks of GCC stage 1.

**Comment by er-1** [comment]
gcc/REVISION may not match with the requested revision.
In revision 259582, gcc/REVISION contains 259562.

contrib/gcc_update --touch doesn't update gcc/REVISION.
contrib/gcc_update updates gcc/REVISION but it pulls newer files which means it's not the wanted revision any longer.

$ gcc-7-branch> svn info
Path: .
Working Copy Root Path: /home/erwan/tmp/at-build-tray/sources/gcc-7-branch
URL: svn://gcc.gnu.org/svn/gcc/branches/ibm/gcc-7-branch
Relative URL: ^/branches/ibm/gcc-7-branch
Repository Root: svn://gcc.gnu.org/svn/gcc
Repository UUID: 138bc75d-0d04-0410-961f-82ee72b054a4
Revision: 259582
Node Kind: directory
Schedule: normal
Last Changed Author: pc
Last Changed Rev: 259582
Last Changed Date: 2018-04-23 18:14:38 -0300 (Mon, 23 Apr 2018)

$ gcc-7-branch> cat gcc/REVISION 
[ibm/gcc-7-branch revision 259562]

I propose this: after the checkout, take the revision number from the svn output to update gcc/REVISION.

**Comment by tuliom** [comment]
The GCC team is clarifying why gcc/REVISION was checked in and what that revision number means.
I like your proposal, but let's wait for their reply.  I suspect the revision number in that file will help to fix the issue 2, where both the revision of branches/ibm/gcc-7-branch and branches/gcc-7-branch are listed.

**Comment by er-1** [comment]
Based on the @peter-bergner's comment, I propose to update the pre hacks of gcc stage 1. It will keep the revision number (from FSF) and add the requested revision number.
Then `gcc -v` will display something like this: 
`gcc version 7.3.1 20180423 (Advance-Toolchain-at11.0) [ibm/gcc-7-branch revision 259582, based upon FSF revision 259562] (GCC)`
