### ISSUE TITLE
Run watch_ldconfig as a service after reboot

### ISSUE THREAD

**Issue by cristianomalossi** [advancetoolchain/advance-toolchain#50]
Hi,

I apologize if this issue has been addressed already (I could not find many details): we need to run watch_ldconfig as a service, rather than a process in background, on a Minsky with RHEL7.3

Currently I am running the script below at each reboot, but this is creating an issue with some new postboot scripts that check for completition.

```
version=9.0

# ENABLE WATCH LD CONFIG
if pgrep -u root -f /opt/at$version/bin/watch_ldconfig > /dev/null
then
    echo "AT$version WATCH LD CONFIG ALREADY RUNNING"
else
    /opt/at$version/bin/watch_ldconfig &
	echo "AT$version WATCH LD CONFIG ENABLED"
fi
```

I see there was a commit 24 days ago in this direction here:
https://github.com/advancetoolchain/advance-toolchain/commit/eff32146075d338175becf2b5856a1029b41cfb9

What I should do to make use of this change and enable the service after each reboot? I need this for AT8.0, AT9.0, AT10.0

Many thanks,

Cristiano MALOSSI

> Research Staff Member
> IBM Research - Zurich
> Foundations of Cognitive Solutions
> Säumerstrasse 4, 8803 Rüschlikon - Switzerland
> tel: +41 44 724 8616
> e-mail: acm@zurich.ibm.com
> www: http://ibm.biz/cristiano_malossi

**Comment by rzinsly** [comment]
Hi,

This will be available in the next AT releases, starting with AT 10.0-4.
We didn't change this on AT 8.0, we only do security updates in it. Notice that AT 8.0 is reaching the end of life as we release AT 11.0.

**Comment by cristianomalossi** [comment]
Hi,

Thank you for the clarification. Could you please enable it also for AT9, we have a lot of tools currently using it.

Concerning AT8, are you aware that IBM Streams currently works only with this version of AT? This is the only reason why we still have AT8 installed. Otherwise we would not use it anymore.

**Comment by rzinsly** [comment]
It will be available in the next AT 9.0 release as well. :)

I advice anyone using AT 8.0 to upgrade to the latest AT as possible. All archs and distros supported by AT 8.0 are supported by AT 9.0 and most are supported by AT 10.0.
I know some people still use AT 8.0 but we are not able to provide the same level of support we provide for newer versions.
Contributions are always welcome, however we may not be able to provide official builds of old AT versions.

**Comment by cristianomalossi** [comment]
Thank you

**Comment by rzinsly** [comment]
Closing this as all supported AT versions have it.
