### ISSUE TITLE
ATnext fails in mpfr preconfigure on Ubuntu 18.04

### ISSUE THREAD

**Issue by munroesj52** [advancetoolchain/advance-toolchain#521]
Tried to build ATnext on Ubuntu 18.04 

autoreconf: running: /usr/bin/autoconf --force --warnings=all,error
configure:14765: error: possibly undefined macro: AX_PTHREAD
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

Seems to be related to this reported issue: 
https://stackoverflow.com/questions/17055279/autotools-for-pthreads-not-setting-correct-linker-flags

**Comment by tuliom** [comment]
This is duplicated with issue #243 . 
You have to install autoconf-archive in order to fix this.
