### ISSUE TITLE
advance-toolchain-at10.0-runtime_10.0-4 update over 10.0-3: watch_ldconfig conflict

### ISSUE THREAD

**Issue by grooverdan** [advancetoolchain/advance-toolchain#53]
<pre>
Preparing to unpack .../advance-toolchain-at10.0-runtime_10.0-4_ppc64el.deb ...
Unpacking advance-toolchain-at10.0-runtime (10.0-4) over (10.0-3) ...
dpkg: error processing archive /var/cache/apt/archives/advance-toolchain-at10.0-runtime_10.0-4_ppc64el.deb (--unpack):
 trying to overwrite '/opt/at10.0/bin/watch_ldconfig', which is also in package advance-toolchain-at10.0-devel 10.0-3
AT's linker cache file is not automatically updated when a package is installed or modified.
Please run /opt/at10.0/bin/watch_ldconfig or reboot your system if you want it to be.
Processing triggers for libc-bin (2.23-0ubuntu7) ...
Errors were encountered while processing:
 /var/cache/apt/archives/advance-toolchain-at10.0-runtime_10.0-4_ppc64el.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
<pre>

Removing the old -devel package and reinstalling it worked

**Comment by rzinsly** [comment]
This is a know issue, watch_ldconfig was distributed in the devel package by mistake, we fixed this now and unfortunately it's not possible to update to newer AT versions if you have the devel package installed.
