### ISSUE TITLE
Fedora22 RPM builds unsigned and still on 10.0-1

### ISSUE THREAD

**Issue by grooverdan** [advancetoolchain/advance-toolchain#54]
<pre>
cat /etc/yum.repos.d/at.repo

[at]
name=Advance Toolchain Unicamp FTP
baseurl=ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/redhat/Fedora22
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/redhat/Fedora22/gpg-pubkey-6976a827-5164221b
       ftp://ftp.unicamp.br/pub/linuxpatch/toolchain/at/redhat/RHEL6/gpg-pubkey-3052930d-5175955a

$ sudo dnf install advance-toolchain-at10.0-cross-ppc64 advance-toolchain-at10.0-cross-ppc64le
======================================================================================================================================================================
 Package                                                     Arch                        Version                                  Repository                     Size
======================================================================================================================================================================
Installing:
 advance-toolchain-at10.0-cross-common                       x86_64                      10.0-1                                   at                            5.3 M
 advance-toolchain-at10.0-cross-ppc64                        x86_64                      10.0-1                                   at                            297 M
 advance-toolchain-at10.0-cross-ppc64le                      x86_64                      10.0-1                                   at                            261 M

...
Is this ok [y/N]: y
Downloading Packages:
[SKIPPED] advance-toolchain-at10.0-cross-ppc64-10.0-1.x86_64.rpm: Already downloaded
[SKIPPED] advance-toolchain-at10.0-cross-common-10.0-1.x86_64.rpm: Already downloaded
[SKIPPED] advance-toolchain-at10.0-cross-ppc64le-10.0-1.x86_64.rpm: Already downloaded
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Package advance-toolchain-at10.0-cross-ppc64-10.0-1.x86_64.rpm is not signed
</pre>

dnf --nogpgcheck is sufficient to get the RPMs installed.

**Comment by rzinsly** [comment]
Thanks,
We updated the packages to 10.0-4 but the cross compiler files are still not signed.
The will be in the next versions.

**Comment by rzinsly** [comment]
AT 10.0-5 was released with the cross packages signed.
