### ISSUE TITLE
Remove OProfile and Libpfm from AT next

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#642]
IBM Advance Toolchain 12.0 will be the last version that includes OProfile and Libpfm.

Future versions of IBM Advance Toolchain will not include OProfile nor Libpfm in favor of [the Linux perf command and the perf_events set of performance tools](https://perf.wiki.kernel.org/index.php/Main_Page) available from the supported distributions.

**Comment by tuliom** [comment]
Cherbot must be modified before this removal happens.

**Comment by er-1** [comment]
On Cherbot, the following will be applied:
```
diff --git a/update-at/update-at b/update-at/update-at
index 32132e1..a37e014 100644
--- a/update-at/update-at
+++ b/update-at/update-at
@@ -9,7 +9,6 @@ glibc
 # TODO: Review this after diverging AT 12.0/next.
 # libdfp
 libhugetlbfs
-libpfm
 libsphde
 liburcu
 # TODO: Review this after diverging AT 12.0/next.
@@ -17,7 +16,6 @@ liburcu
 mpc
 mpfr
 openssl
-oprofile
 paflib
 python
 tbb
```
