### ISSUE TITLE
Can't build if dependencies not installed via rpm

### ISSUE THREAD

**Issue by benmenadue** [advancetoolchain/advance-toolchain#66]
We have installed the IBM Java SDK is installed via `.bin` from https://developer.ibm.com/javasdk/downloads/sdk7r1/ but it still reports `Couldn't find (ibm-java2-ppc64le-sdk-7.1|java-1.7.1-ibm-devel) required to proceed the build.` when attempting to build.

We can't use pre-build RPMs because installing in `/opt` doesn't work on our system (we instead use network-mounted `/apps` for this sort of thing), and the RPMs are not relocatable.

**Comment by tuliom** [comment]
@benmenadue This is a very specific scenario of your environment.
Can't you modify your own distro file to adhere to this requirement? e.g. changing `AT_NATIVE_PKGS_REQ` and `AT_NATIVE_PGMS_REQ` from configs/11.0/distros/redhat-7.mk.
