### ISSUE TITLE
AT12  //   GLIBC_2.22 not found 

### ISSUE THREAD

**Issue by brucesemple** [advancetoolchain/advance-toolchain#683]
Full message ==> /lib64/ld64.so.2: version `GLIBC_2.22' not found (required by /opt/at12.0/lib64/power9/libc.so.6)

when I update my LD_LIBRARY_PATH to LD_LIBRARY_PATH=/opt/at12.0/lib64:/usr/lib64:/usr/lib

and then try to run a wget, or start Mongod    I get this library not found message.  This is on a Centos System.   I'm building a Docker image to run on a P9 box.
Any ideas?

**Comment by ThinkOpenly** [comment]
Two questions:
- Why are you updating the `LD_LIBRARY_PATH`?  Do you need to?
- Note that it's looking for `/lib64/ld64.so.2`, but that path, `/lib64` is not in your `LD_LIBRARY_PATH`. Is there a reason that was excluded?

**Comment by tuliom** [comment]
@brucesemple were both wget and mongod built with the Advance Toolchain 12.0?

**Comment by brucesemple** [comment]
I don't know.  However, I was under the impression that you could just swap in the  ATC runtime libraries to replace the default C/C++ runtime libraries and hopefully just get better performance.

**Comment by tuliom** [comment]
@brucesemple No.  These executables are using the system loader with the Advance Toolchain libraries.  That's what's causing the error.  We have some suggestions for you here: https://developer.ibm.com/linuxonpower/advance-toolchain/advtool-faq#tab_faq6

**Comment by tuliom** [comment]
I'm closing this issue.
If you have any other questions, feel free to reopen or add more comments.
