### ISSUE TITLE
Filter the at_downloader.sh downloads by arch

### ISSUE THREAD

**Issue by rzinsly** [advancetoolchain/advance-toolchain#7]
AT Downloader currently download all packages from a directory of our repository.
The users should be able to choose if they want to download ppc64 or ppc64le packages, it is not necessary to download the cross compiler packages.

**Comment by racardoso** [comment]
I already finish the basic implementation as you can see at https://github.com/racardoso/advance-toolchain/tree/enhance-at-downloader (commits https://github.com/racardoso/advance-toolchain/commit/0235e6c4924381a33d0df789fcfb6efc6a33af45 and https://github.com/racardoso/advance-toolchain/commit/7b0f660142beed89cfa7245d39e11532471e2553)

There's still some missing things to do:

1. Use `uname -m` or `arch` to get the user machine and check on arch list if there's on the list. If so select this as default
2. The implementation list all architectures include the cross compiles. Check if you have to give a option to download it or if you have to filter it and do not list cross compiles
3. On debian/ubuntu you need to check if there's any packages inside the folder `binary-*` before list arch options (i386 on debian has a empty folder and should not be listed and currently it is.
4. After all you just have to append `${at_arch} `to download string.

@rpsene will assume this task.
