### ISSUE TITLE
Generate manpages for Valgrind

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#767]
During the pre-install phase of Valgrind, the HTML documentation is generated, but it misses the manpages that are provided by Makefile target `man-pages` in `docs/`.

**Comment by er-1** [comment]
@tuliom which versions of AT are concerned?
I think to make on AT 10.0 and newer versions.

**Comment by tuliom** [comment]
@er-1 Yes, it's indeed AT >= 10.0.
