### ISSUE TITLE
Optimize zlib for POWER8 on AT 12.0

### ISSUE THREAD

**Issue by tuliom** [advancetoolchain/advance-toolchain#780]
Please include https://github.com/madler/zlib/pull/335 in the zlib build in order to get the performance optimization from that PR.

**Comment by mscastanho** [comment]
Is this still relevant now that #1341 has been merged? That PR applies the optimizations only to AT next (14.0), but we likely don't need it anymore for 12.0 anyway.

**Comment by tuliom** [comment]
I expected to have these optimizations at least on the last active AT release (13.0).
By the time this issue was opened, it was AT 12.0.

**Comment by tuliom** [comment]
@mscastanho I've just realized that #1341 has not been applied even to AT 14.0.

**Comment by mscastanho** [comment]
@tuliom true. I'll take care of that.

**Comment by Neustradamus** [comment]
Note: Now there is zlib 1.2.13 with CVE fixes.
