### ISSUE TITLE
at11.0-alpha2 strict aliasing warning

### ISSUE THREAD

**Issue by grooverdan** [advancetoolchain/advance-toolchain#82]
Please include the master branch patch from https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80593

**Comment by grooverdan** [comment]
https://github.com/gcc-mirror/gcc/commit/84cc4af9cbab6eda3c800a22f7c760e76913b506

**Comment by tuliom** [comment]
The GCC update from pull request #119 will automatically get this.

**Comment by tuliom** [comment]
It should be fixed with commit e1a3bd097737.

**Comment by grooverdan** [comment]
thanks.
