### ISSUE TITLE
missing software-defined tracepoints

### ISSUE THREAD

**Issue by ThinkOpenly** [advancetoolchain/advance-toolchain#946]
A colleague has been trying to use `splat` (https://github.com/open-power-sdk/splat) with an application compiled and linked with Advance Toolchain.  `splat` is a wrapper around the `perf` command which makes use of "software defined tracepoints" (SDTs).  SDTs are predefined tracepoints in user-level/library code which can be enabled and used to do system-wide tracing on user-mode symbols.

Glibc has SDTs defined for many things, including what `splat` uses:  various `pthread_mutex` function calls.  I'm not an expert here, but from what I've found (looking at the code for the `perf` command, the SDT definitions show up in an ELF "note" section in the library.  Some evidence to support that:
```
$ readelf --notes /lib64/libpthread-2.17.so | grep sdt | wc -l
115
```
 
I'm not seeing the same information in the corresponding Advance Toolchain library:
```
$ readelf --notes /opt/at12.0/lib64/libpthread-2.28.so | grep sdt | wc -l
0
```
 
It looks like, in this case, glibc's `configure` script will enable the generation of SDTs by looking for `<sys/sdt.h>` and successfully compiling a small test case with it.  The script ensures that `USE_STAP_PROBE` is defined for the glibc build if that test case works.  `USE_STAP_PROBE` is then used in glibc's `include/stap-probe.h`, which defines `LIBC_PROBE`, which is the macro used to generate these various SDTs, as can be seen in glibc's `nptl/pthread_mutex_init.c`, for example.

I think there is a simple fix, and that is to make sure the build systems have the packages installed that include `sys/sdt.h`.
On Red Hat:  `systemtap-sdt-devel`
On Ubuntu: `systemtap-sdt-dev`
 
I tried to figure out where a dependency should be added, to avoid this in the future, and I think it would be in `configs/*/distros/*`, but I want to confirm because I am not sure.

**Comment by er-1** [comment]
On AT next, after applying a patch, I got this:
```
$ readelf --notes ./opt/at-next-13.0-0-alpha/lib64/libpthread-2.29.9000.so | grep sdt | wc -l
33
```
I'll refine my patch and send a PR.
