### ISSUE TITLE
debuginfo file locations are not generally useful

### ISSUE THREAD

**Issue by ThinkOpenly** [advancetoolchain/advance-toolchain#965]
The Advance Toolchain debuginfo packages place their files in `/opt/at{version}/lib/debug/opt/at{version}/lib64`. To be generally useful, for example by `gdb` or `perf`, the following algorithm should be observed (from https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html).

For a library `/opt/atversion/lib64/libA.so`, with "debug link" `libA.so.debug` and "build-id" `abcdef`, its corresponding debuginfo file will be looked for at the following locations, in order:
1. `/usr/lib/debug/.build-id/ab/cdef/.debug`
1. `/opt/atversion/lib64/libA.so.debug`
1. `/opt/atversion/lib64/.debug/libA.so.debug`
1. `/usr/lib/debug/opt/atversion/lib64/libA.so.debug`

The current location of the Advance Toolchain debuginfo files will not match any of those locations.

If there is a strong desire to avoid putting files in `/usr`, then the following options are reasonable locations that will work in general:
1. `/opt/atversion/lib64/libA.so.debug`
1. `/opt/atversion/lib64/.debug/libA.so.debug`

_Note that the `gdb` that is included with Advance Toolchain works because in addition to `/usr/lib/debug`, it is apparently modified to include an additional "global debug directory" of `/opt/at{version}/lib/debug`._

All that being said, an `strace` of `perf` shows the only attempt to find a debuginfo file in `/opt` was for `/opt/at{version}/lib64/.debug/libA.so`.  (Note there is no `.debug` appended.)  So, some testing is warranted.

**Comment by ThinkOpenly** [comment]
Are there any objections to `/opt/at{version}/lib64/.debug/libA.so` ?
(I confess I don't know how the current location (`/opt/at{version}/lib/debug/opt/at{version}/lib64`) was selected, and if changing from that location will break anything?)

**Comment by ThinkOpenly** [comment]
Notes for testing:
- gdb
  ```
  being able to statement step through libc routines (even if the source can't be found)
  ```
- valgrind
  ```
  valgrind --tool=memcheck --leak-check=full strdup
  ```
- perf
  ```
  $ perf probe -x /opt/at11.0/lib64/libpthread.so.0 --force --add=pthread_mutex_trylock mutex --add=pthread_mutex_trylock_ret=pthread_mutex_trylock%return $retval 
  The /opt/at11.0/lib64/libpthread-2.26.so file has no debug information.
  Rebuild with -g, or install an appropriate debuginfo package.
    Error: Failed to add events.
  ```

**Comment by rzinsly** [comment]
> Are there any objections to `/opt/at{version}/lib64/.debug/libA.so` ?

I don't see a problem with that.

> (I confess I don't know how the current location (`/opt/at{version}/lib/debug/opt/at{version}/lib64`) was selected, and if changing from that location will break anything?)

I don't remember why this location was selected, gdb can is configured with --with-separate-debug-dir this may not be necessary anymore with this change.
